### ISSUE TITLE
Formulario Mantenedor Nave

### ISSUE THREAD

**Issue by kristobal1** [GetItDone-GID/sistematatc#18]

**Comment by IvanArancibia** [comment]
Este mantenedor tiene como objetivo mostrar la información de las naves. En este mantenedor el usuario podrá agregar, editar y exportar la información.

**Comment by IvanArancibia** [comment]
Pantalla Principal: En esta pantalla el usuario tendrá acceso a la información de las naves ingresadas. De lo cual podemos describir lo siguiente:

•	IMO CODE: Muestra el código asignado a la nave.
•	Nombre: Muestra el nombre de la nave.
•	Bandera: Muestra el país al cual pertenece la nave.
•	Callsing: 
•	Estado: Muestra el estado en el cual se encuentra, este puede ser Activo/No Activo.
•	Opciones: El usuario tendra la opción de editar la nave seleccionado.

**Comment by kristobal1** [comment]
En primera instancia desde el menú se redirecciona a un formulario "no modal" el cual funciona como una búsqueda, y por defecto lista todos los datos relacionados. (similar al sistema Siscovent)
![image](https://user-images.githubusercontent.com/48256533/122622015-55853680-d065-11eb-867b-f3e3cf7cea2e.png)
este primer formulario debe considerar

- [ ] Grilla que liste los datos
- [ ] En columna final agregar opción de editar y eliminar.
- [ ] Sobre la grilla debe existir una búsqueda tipo LIKE, que con cada clic busque semejanza en la grilla.
- [ ] En la esquina inferior derecha botón AGREGAR
- [ ] Sobre la grilla a mano izquierda, botón que permita exportar a EXCEL la grilla.

Al hacer clic en agregar o editar, se abrira un Modal, sobre el cual se pueda gestionar la creacion o edicion del articulo.

![image](https://user-images.githubusercontent.com/48256533/122622264-2622f980-d066-11eb-8059-16fa63240e9b.png)
