### ISSUE TITLE
Control de usuario

### ISSUE THREAD

**Issue by kristobal1** [GetItDone-GID/sistematatc#29]
Login del sistema

**Comment by katacliny** [comment]
Una pequeña description de las tareas a ejecutar para completar esta task.

- [ ] Crear el endpoint en el back end en el proyecto de auth, usar por favor esta librería de python https://django-rest-auth.readthedocs.io/en/latest/installation.html note que esta librerías tiene 3 dependencias definidas en la doc que Tambien hay que instalar
- [ ] Actualizar el requirements.txt file con las nuevas librerías añadidas
- [ ] En el front crear las pantallas (Create, Update, Delete) para al gestión de usuarios 
- [ ] En el front crear los formularios para las pantallas Create Update Delete por favor usa resta librería la cual esta ya instalada en el proyecto cliente de react tener en cuenta la gestión de errores 
- [ ] En el front crear todas las llamadas necesarias a la api para gestionar los usuarios
- [ ] En el front crear la pantalla de login
- [ ] En el front crear el formulario de login
- [ ] En el front crear todas las llamadas a la api para el login y gestionar los errores 
- [ ] Para las llamadas a la api desde el front por favor usar fetch https://developer.mozilla.org/es/docs/Web/API/Fetch_API/Using_Fetch
- [ ] Los nuevos componentes react que se añadan por favor usar hooks y componentes basados en funciones https://es.reactjs.org/docs/components-and-props.html https://es.reactjs.org/docs/hooks-intro.html

**Comment by katacliny** [comment]
>

**Comment by katacliny** [comment]
[](https://www.youtube.com/watch?v=w7ejDZ8SWv8)

**Comment by katacliny** [comment]
[Un pequeño curso de react](https://www.youtube.com/watch?v=w7ejDZ8SWv8)
