### ISSUE TITLE
Menu de sistema

### ISSUE THREAD

**Issue by kristobal1** [GetItDone-GID/sistematatc#35]
Debe ser menú lateral, acompañado de un nav superior el cual administre logout y administrar datos personales de usuario
Como ejemplo el sistema Siscovent
![image](https://user-images.githubusercontent.com/48256533/122621213-db53b280-d062-11eb-95e5-e142c0c4bcb4.png)
Todos los mantenedores son submenu del menú "Mantenedor" y los formularios asociados a un proceso de TATC o TSTC tienen un menú independiente

**Comment by esteban1991** [comment]
Utilizaremos  este tipo de menu, siguiendo el diseño ya mencionado como syscovent
![image](https://user-images.githubusercontent.com/35140961/126488468-4088a46a-de05-4d79-898c-281bcd365338.png)
no puede ser igual ya que viene de otro proyecto, pero la idea es agruparlo de maneral similar
hay que verificar el tema de permisos que puede y no se puede ver
